---
- name: Install tree package
  hosts: all
  become: yes
  tasks:
    - name: Install tree (Ubuntu)
      ansible.builtin.apt:
        name: tree
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install tree (RHEL)
      ansible.builtin.yum:
        name: tree
        state: present
      when: ansible_os_family == "RedHat"
